env:
  node: true
  browser: true
  es2021: true
extends:
  - "airbnb-base"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  no-param-reassign: 0
  no-shadow: 0
  import/no-cycle: 0
  object-curly-newline: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  max-len: [2, {"code": 280, "tabWidth": 4, "ignoreUrls": true}]
  no-underscore-dangle: [ 2, { "allow": [ "__filename", "__dirname" ] } ]
  import/no-unresolved: 0
  import/prefer-default-export: 0
