export const renderText = (i18n) => {
  const header = document.querySelector('.header');
  const title = header.querySelector('.display-3');
  title.innerHTML = `<i class="bi bi-rss"></i>${i18n.t('titleHeader')}`;
  const lead = header.querySelector('.lead');
  lead.textContent = i18n.t('description');
  const urlInput = header.querySelector('#url-input');
  urlInput.setAttribute('placeholder', `${i18n.t('placeholder')}`);
  const btn = header.querySelector('.btn');
  btn.innerHTML = `<i class="bi bi-rss"></i>${i18n.t('posts.button')}`;
  const example = header.querySelector('.example');
  example.textContent = i18n.t('example');
  const feedback = header.querySelector('.feedback');
  feedback.textContent = i18n.t('translation.messages.success');
  const main = document.querySelector('.main');
  const postsTitle = main.querySelector('.posts-title');
  postsTitle.textContent = i18n.t('posts.posting');
  const feedsTitle = main.querySelector('.feeds-title');
  feedsTitle.textContent = i18n.t('feeds.title');
  const newLessons = main.querySelector('.new-lessons');
  newLessons.textContent = i18n.t('posts.newLessons');
  const practicalLessons = main.querySelector('.practical-lessons');
  practicalLessons.textContent = i18n.t('posts.practicalLessons');
  const modal = document.querySelector('.modal');
  const modalTitle = modal.querySelector('.modal-title');
  modalTitle.textContent = i18n.t('modal.modalTitle');
  const read = modal.querySelector('.read');
  read.textContent = i18n.t('modal.read');
  const close = modal.querySelector('.close-btn');
  close.textContent = i18n.t('modal.close');
};
