export const renderText = (resources) => {
  const lng = resources.ru;
  const header = document.querySelector('.header');
  const title = header.querySelector('.display-3');
  title.innerHTML = `<i class="bi bi-rss"></i>${lng.titleHeader}`;
  const lead = header.querySelector('.lead');
  lead.textContent = lng.description;
  const urlInput = header.querySelector('#url-input');
  urlInput.setAttribute('placeholder', `${lng.placeholder}`);
  const btn = header.querySelector('.btn');
  btn.innerHTML = `<i class="bi bi-rss"></i>${lng.posts.button}`;
  const example = header.querySelector('.example');
  example.textContent = lng.example;
  const feedback = header.querySelector('.feedback');
  feedback.textContent = lng.translation.messages.success;
  const main = document.querySelector('.main');
  const postsTitle = main.querySelector('.posts-title');
  postsTitle.textContent = lng.posts.posting;
  const feedsTitle = main.querySelector('.feeds-title');
  feedsTitle.textContent = lng.feeds.title;
  const newLessons = main.querySelector('.new-lessons');
  newLessons.textContent = lng.posts.newLessons;
  const practicalLessons = main.querySelector('.practical-lessons');
  practicalLessons.textContent = lng.posts.practicalLessons;
  const modal = document.querySelector('.modal');
  const modalTitle = modal.querySelector('.modal-title');
  modalTitle.textContent = lng.modal.modalTitle;
  const read = modal.querySelector('.read');
  read.textContent = lng.modal.read;
  const close = modal.querySelector('.close-btn');
  close.textContent = lng.modal.close;
};
